config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root 'boards#new'
  get '/boards', to: 'boards#home', as: 'boards'
  get '/boards/index', to: 'boards#index', as: 'board_index'
  post '/boards', to: 'boards#create'
  get '/boards/:id', to: 'boards#show', as: 'board'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/board.rb
require 'json'

class Board < ApplicationRecord
  validates :width, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validates :height, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validates :num_mines, presence: true, numericality: { only_integer: true, greater_than: 0, less_than_or_equal_to: :max_mines }
  validates :board_name, presence: true
  validates :email, presence: true, format: { with: URI::MailTo::EMAIL_REGEXP }
  validates :generate_board, presence: true

  def max_mines
    width * height
  end

  def random_bomb
    @positions = []
    (0..(height - 1)).each do |i|
      (0..(width - 1)).each do |j|
        @positions << [i, j]
      end
    end
    @positions = @positions.shuffle.first(num_mines)
  end

  def generate_board
    random_bomb
    if num_mines > (width * height)
      return []
    else
      board = Array.new(height) { Array.new(width, 0) }
      @positions.each do |i, j|
        board[i][j] = 1
      end
    end
    board.to_json
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  def home
    @boards = Board.order(created_at: :desc).limit(10)
  end

  def index
    @boards = Board.order(created_at: :desc)
  end
  def show
    @board = Board.find(params[:id])
  end

  def new
    @board = Board.new
  end

  def create
    @board = Board.new(board_params)
    if @board.valid?
      @board.board_data = @board.generate_board
      if @board.board_data.present?
        @board.save
        redirect_to board_path(@board), notice: "The board game was created"
      else
        flash[:alert] = "There was an error creating the board"
        redirect_to new_board_path
      end
    else
      render :new, notice: "The board is not valid."
    end
  end

  private

  def board_params
    params.require(:board).permit(:email, :board_name, :width, :height, :num_mines)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/views/boards/home.html.erb
<div class="d-flex justify-content-center align-items-center">
  <div class="card p-4 w-60">
    <div class="card-header">
      <h1 class="text-center">Welcome to Minesweeper</h1>
    </div>
    <div class="card-body">
      <div class="text-center">
        <h2>Recently Generated Boards:</h2>
        <hr class="my-4">
      </div>

      <% @boards.each do |board| %>
        <li><%= link_to board.board_name, board_path(board) %>, generated by <%= board.email %>
          on <%= board.created_at.strftime("%B %d, %Y at %I:%M %p") %></li>
      <% end %>
      <div class="mt-2 ms-4">
        <%= link_to "View All Generated Boards", board_index_path, class: "btn btn-primary"  %>
      </div>
    </div>
  </div>
</div>

app/views/boards/index.html.erb
<% @boards.each do |board| %>
  <div class="card mb-3">
    <div class="card-header align-self-center w-100">
      <h5 class="card-title">Board name: <%= board.board_name %></h5>
    </div>
    <div class="card-body">
      <div class="table-responsive">
        <div class="text-center me-2 ms-2">
          <% if board.board_data %>
            <% JSON.parse(board.board_data).each do |row| %>
              <% row.each do |cell| %>
                <% if cell == 0 %>
                  <i class="fas fa-square fa-3x me-3 ms-2 mt-2" style="width: 48px; height: 48px;"></i>
                <% else %>
                  <i class="fas fa-bomb fa-3x me-2 ms-3" style="width: 48px; height: 48px;"></i>
                <% end %>
              <% end %>
              <br>
            <% end %>
          <% end %>
        </div>
      </div>
      </div>
      <div class="card-footer mt-4">
        <p class="card-text">Generated by: <%= board.email %>
          on <%= board.created_at.strftime("%B %d, %Y at %I:%M %p") %></p>
      </div>
  </div>
<% end %>

app/views/boards/new.html.erb
<%= form_for @board, url: boards_path do |f| %>
  <div class="d-flex justify-content-center align-items-center ">
    <div class="card p-4 w-50">
      <div class="mb-3 ">
        <%= f.label :email, class: "form-label" %>
        <%= f.text_field :email, class: "form-control", required: true %>
      </div>
      <div class="mb-3 ">
        <%= f.label :board_name, class: "form-label" %>
        <%= f.text_field :board_name, class: "form-control", required: true %>
      </div>

      <div class="mb-3 ">
        <%= f.label :width, class: "form-label" %>
        <%= f.number_field :width, class: "form-control", required: true, min: 1, max: 100 %>
      </div>

      <div class="mb-3 ">
        <%= f.label :height, class: "form-label" %>
        <%= f.number_field :height, class: "form-control", required: true, min: 1, max: 100 %>
      </div>

      <div class="mb-3 ">
        <%= f.label :num_mines, class: "form-label" %>
        <%= f.number_field :num_mines, class: "form-control", required: true, in: 1..100 %>
      </div>
      <%= f.submit "Generate Board", class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/boards/show.html.erb
<div class="container mt-5">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <div class="card">
        <div class="card-header">
          <h1 class="text-center">Board name: <%= @board.board_name %></h1>
        </div>
        <div class="card-body">
          <div class="table-responsive">
              <div class="text-center me-2 ms-2">
              <% JSON.parse(@board.board_data).each do |row| %>
                  <% row.each do |cell| %>
                    <% if cell == 0 %>
                       <i class="fas fa-square fa-3x me-3 ms-3 mt-3" style="width: 48px; height: 48px;"></i>
                    <% else %>
                        <i class="fas fa-bomb fa-3x me-3 ms-3" style="width: 48px; height: 48px;"></i>
                    <% end %>
                  <% end %>
                <br>
              <% end %>
              </div>
          </div>
          <div class="mt-2 text-center">
            Generated by: <%= @board.email %> on <%= @board.created_at.strftime("%B %d, %Y at %I:%M %p") %>
          </div>
        </div>
        <div class="card-footer">
          <%= link_to "Back to all generated boards", board_index_path, class: "btn btn-secondary" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MinesweeperBoard</title>
  <%= stylesheet_link_tag 'https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css' %>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>
</head>

<body>
<nav class="navbar navbar-expand-lg bg-body-tertiary bg-info">
  <div class="container-fluid">
    <a class="navbar-brand" href="<%= boards_path %>">Minesweeper</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="<%= boards_path %>">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<%= root_path %>">New Board</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<%= board_index_path %>">All Boards</a>
        </li>
      </ul>
    </div>
  </div>

</nav>
<div class="container">
  <br>
  <br>
  <%= notice %>
  <%= alert %>
  <%= yield %>
</div>
</body>
</html>